pipeline {
 agent none
 stages {
 stage ('Back-end') {
  agent {
   docker { image 'maven:3.9.9-eclipse-temurin-11' }
  }
  steps {
   sh 'mvn --version'
  }
 }
 stage ('Front-end') {
  agent {
   docker { image 'node:18.0-alpine' }
  }
  steps {
   sh 'node --version'
  }
 }
}
}
